exports.APPEAL_STATUS_TYPE_NEW = "NEW";
exports.APPEAL_STATUS_TYPE_ACCEPTED = "ACCEPTED";
exports.APPEAL_STATUS_TYPE_REJECTED = "REJECTED";
exports.APPEAL_STATUS_TYPE_IN_PROGRESS = "INPROGRESS";
exports.APPEAL_STATUS_TYPE_DONE = "DONE";
